language: node_js
node_js:
  - '4'
  - '6'
  - '8'
  - '10'
os:
  - linux
  - windows
matrix:
  fast_finish: true
  allow_failures:
    - os: windows
sudo: false
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer@next | node
install:
  - pnpm i
script:
  - npm t
notifications:
  email: false
